### ISSUE TITLE
Failed to Boot Mariner Cloud Image

### ISSUE THREAD

**Issue by russell-islam** [cloud-hypervisor/rust-hypervisor-firmware#132]
While I was trying to boot Mariner VM image on Microsoft Hypervisor I got the boot failed. I was able to collect the log from emulated serial console.
-----------------------------------------------------------------------------------------------------------------
Setting up 4 GiB identity mapping
Page tables setup

Booting with PVH Boot Protocol
Found PCI device vendor=8086 device=d57 in slot=0
Found PCI device vendor=1af4 device=1043 in slot=1
Found PCI device vendor=1af4 device=1042 in slot=2
Found PCI device vendor=1af4 device=1041 in slot=3
Found PCI device vendor=1af4 device=1044 in slot=4
PCI Device: 0:2.0 1af4:1042
Bar: type=MemorySpace32 address=e7f80000
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=Unused address=0
Virtio block device configured. Capacity: 204800000 sectors
Found EFI partition
Filesystem ready
Error loading default entry: FileError(NotFound)
Using EFI boot.
Found bootloader (BOOTX64.EFI)
Executable loaded
TPM logging failed: Unsupported
Could not create MokListRT: Unsupported
TPM logging failed: Unsupported
Could not create MokListXRT: Unsupported
Something has gone seriously wrong: import_mok_state() failed: Unsupported
TPM logging failed: Unsupported
Reloc 0 block size 0 is invalid
Relocation failed: Unsupported
Failed to load image: Unsupported
start_image() returned Unsupported
PANIC: panicked at 'Unable to boot from any virtio-blk device', src/main.rs:188:5

**Comment by russell-islam** [comment]
@liuw @rbradford FYI

**Comment by liuw** [comment]
It looks like BOOTX64.efi is the shim. The shim failed to relocate grubx64.efi.

I'm not sure why the firmware matters in this scenario. Perhaps I have not grasped the whole picutre.

**Comment by retrage** [comment]
As @liuw said, the failure occurred in shim. I don't know which version is used, but [this line](https://github.com/rhboot/shim/blob/05875f3aed1c90fe071c66de05744ca2bcbc2b9e/pe.c#L109) is the corresponding error output in the latest main branch.

@russell-islam Before we take a look closer, can you try booting the VM image with OVMF? If it also fails to boot, the issue is not Rust Hypervisor Firmware specific.

**Comment by russell-islam** [comment]
> As @liuw said, the failure occurred in shim. I don't know which version is used, but [this line](https://github.com/rhboot/shim/blob/05875f3aed1c90fe071c66de05744ca2bcbc2b9e/pe.c#L109) is the corresponding error output in the latest main branch.
> 
> @russell-islam Before we take a look closer, can you try booting the VM image with OVMF? If it also fails to boot, the issue is not Rust Hypervisor Firmware specific.

@retrage I was able to boot with OVMF and successfully run the Kubernetes conformance test.

**Comment by retrage** [comment]
@russell-islam Sorry for the late reply. It's apparently this firmware-specific.

I think it happens with the version of the GRUB used by the Marine VM and the Rust Hypervisor Firmware combination. I confirmed that the latest Ubuntu 21.10 VM image (shim 15.4-0ubuntu2, grub 2.04-1ubuntu45) works fine. As far as I dug the CBL-Mariner repository, it uses shim 15.4 and grub 2.06~rc1. The main difference is the GRUB version.
I'm not sure why shim fails to relocate the GRUB image on loading only when the firmware is used, because the shim has its own PE loader, it does not rely on EFI's LoadImage(). One possible root cause is the VirtIO device driver or the FAT filesystem. Another common mistake is feeding compressed VM to the firmware. Did you decompress the VM?

Anyway, it will be helpful to provide the VM image for reproducing the issue and debugging.

**Comment by retrage** [comment]
@russell-islam Any updates?

**Comment by russell-islam** [comment]
@retrage Could you please provide me your email address and I can share the image.

**Comment by russell-islam** [comment]
@retrage  Did you get the mariner VM image? Any update on testing on your side?

**Comment by retrage** [comment]
@russell-islam Yes, I replied to the e-mail. Thank you for sharing it. I started debugging it the last weekend. I confirmed that the issue is reproduced in my local environment. I'm still looking into the root cause. I found that the loaded `grubx64.efi` image is incomplete as `Reloc 0 block size 0 is invalid` indicates.

**Comment by retrage** [comment]
@russell-islam  It looks like because of the FAT12 filesystem mishandling in the corner case. With some quick fixes, the VM image can boot from the firmware:

```
Welcome to GRUB!

  Booting `CBL-Mariner'

TPM/TPM2 protocols are not provided
EFI stub: ERROR: Failed to locate PCI I/O handles'

Welcome to CBL-Mariner 1.0.20210331 (x86_64) - Kernel 5.10.21.1-rolling-lts-mari
ner-3.cm1 (ttyS0)
mcr-msk8s-1-20-5-machine login:
```

I'll send a PR regarding the fixes.

**Comment by retrage** [comment]
@russell-islam The PR has been merged into the master branch. Please try it out.

**Comment by retrage** [comment]
@russell-islam Please close this issue if you confirmed the fix.

**Comment by russell-islam** [comment]
I have verified the latest version with Mariner Cloud image and it boots fine now.
